// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: stream.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StreamClient is the client API for Stream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamClient interface {
	Single(ctx context.Context, opts ...grpc.CallOption) (Stream_SingleClient, error)
	Multiple(ctx context.Context, opts ...grpc.CallOption) (Stream_MultipleClient, error)
}

type streamClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamClient(cc grpc.ClientConnInterface) StreamClient {
	return &streamClient{cc}
}

func (c *streamClient) Single(ctx context.Context, opts ...grpc.CallOption) (Stream_SingleClient, error) {
	stream, err := c.cc.NewStream(ctx, &Stream_ServiceDesc.Streams[0], "/pb.Stream/Single", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamSingleClient{stream}
	return x, nil
}

type Stream_SingleClient interface {
	Send(*SingleRequest) error
	Recv() (*SingleResponse, error)
	grpc.ClientStream
}

type streamSingleClient struct {
	grpc.ClientStream
}

func (x *streamSingleClient) Send(m *SingleRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamSingleClient) Recv() (*SingleResponse, error) {
	m := new(SingleResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamClient) Multiple(ctx context.Context, opts ...grpc.CallOption) (Stream_MultipleClient, error) {
	stream, err := c.cc.NewStream(ctx, &Stream_ServiceDesc.Streams[1], "/pb.Stream/Multiple", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamMultipleClient{stream}
	return x, nil
}

type Stream_MultipleClient interface {
	Send(*MultipleRequest) error
	Recv() (*MultipleResponse, error)
	grpc.ClientStream
}

type streamMultipleClient struct {
	grpc.ClientStream
}

func (x *streamMultipleClient) Send(m *MultipleRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamMultipleClient) Recv() (*MultipleResponse, error) {
	m := new(MultipleResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamServer is the server API for Stream service.
// All implementations should embed UnimplementedStreamServer
// for forward compatibility
type StreamServer interface {
	Single(Stream_SingleServer) error
	Multiple(Stream_MultipleServer) error
}

// UnimplementedStreamServer should be embedded to have forward compatible implementations.
type UnimplementedStreamServer struct {
}

func (UnimplementedStreamServer) Single(Stream_SingleServer) error {
	return status.Errorf(codes.Unimplemented, "method Single not implemented")
}
func (UnimplementedStreamServer) Multiple(Stream_MultipleServer) error {
	return status.Errorf(codes.Unimplemented, "method Multiple not implemented")
}

// UnsafeStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServer will
// result in compilation errors.
type UnsafeStreamServer interface {
	mustEmbedUnimplementedStreamServer()
}

func RegisterStreamServer(s grpc.ServiceRegistrar, srv StreamServer) {
	s.RegisterService(&Stream_ServiceDesc, srv)
}

func _Stream_Single_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServer).Single(&streamSingleServer{stream})
}

type Stream_SingleServer interface {
	Send(*SingleResponse) error
	Recv() (*SingleRequest, error)
	grpc.ServerStream
}

type streamSingleServer struct {
	grpc.ServerStream
}

func (x *streamSingleServer) Send(m *SingleResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamSingleServer) Recv() (*SingleRequest, error) {
	m := new(SingleRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Stream_Multiple_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServer).Multiple(&streamMultipleServer{stream})
}

type Stream_MultipleServer interface {
	Send(*MultipleResponse) error
	Recv() (*MultipleRequest, error)
	grpc.ServerStream
}

type streamMultipleServer struct {
	grpc.ServerStream
}

func (x *streamMultipleServer) Send(m *MultipleResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamMultipleServer) Recv() (*MultipleRequest, error) {
	m := new(MultipleRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Stream_ServiceDesc is the grpc.ServiceDesc for Stream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Stream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Stream",
	HandlerType: (*StreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Single",
			Handler:       _Stream_Single_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Multiple",
			Handler:       _Stream_Multiple_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "stream.proto",
}
